name: Beaker Image Builder
description: The Beaker Image Builder builds Docker images and creates Beaker images.
inputs:
  dockerfile:
    description: Path to the Dockerfile.
    required: false
    default: 'Dockerfile'
  beakerToken:
    description: Beaker user token. This should be stored as a repository secret.
    required: true
  beakerWorkspace:
    description: | 
      Workspace to place the build image.
      If not provided, the default workspace will be used.
    required: false
runs:
  using: docker
  image: Dockerfile