name: Beaker Image Builder
description: The Beaker Image Builder builds Docker images and creates Beaker images.
inputs:
  dockerfile:
    description: Path to the Dockerfile.
    required: false
    default: 'Dockerfile'
  beaker_token:
    description: Beaker user token. This should be stored as a repository secret.
    required: true
  beaker_workspace:
    description: | 
      Workspace to place the build image.
      If not provided, the default workspace will be used.
    required: false
  beaker_image_name:
    description: |
      Name for the image.
      If omitted, the image will not be named.
      Note that image names must be unique.
    required: false
  github_token:
    description: |
      GitHub token is used to authenticate with the GitHub Package Registry for caching
      Docker builds. This is optional. Caching will be disabled if it is not provided.
outputs:
  image_id:
    description: Beaker image ID.
runs:
  using: docker
  image: Dockerfile